services:
  - type: web
    name: telegram-cpanel-channel-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: STREAM_SECRET
        sync: false
      - key: CPANEL_WATCH_URL
        sync: false
      - key: PUBLIC_BOT_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: TOKEN_TTL_SECONDS
        value: "31536000"
      - key: TARGET_CHANNEL_ID
        value: "-1003956038160"
      - key: CPANEL_INGEST_URL
        sync: false
      - key: CPANEL_INGEST_SECRET
        sync: false
      - key: CPANEL_MEDIA_URL
        value: "https://chalchitra.site/tgstreamnode/media"
